const bcrypt = require("bcrypt");
const SALT_ROUNDS = 10;

module.exports = async () => {
  const defaultPassword = await bcrypt.hash("password", SALT_ROUNDS);
  const adminPassword = await bcrypt.hash("123", SALT_ROUNDS);
return [
  { id: 1, is_admin: true, username: "EmperorMatthew", first_name: "Matthew", last_name: "Wegenke", email: "abc@gmail.com", password: adminPassword, rank: "General", gender: "Male", age: 67, xp: 2500, rival_ids: [2, 3, 4], badges_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], titles_ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], cosmetic_ids: [3, 4, 10, 12], profile: '{"color":"/Avatar/color/image (1).png","base":"/Avatar/male.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 2, username: "MajorDisaster", first_name: "John", last_name: "Miller", email: "vanguard@gmail.com", password: defaultPassword, rank: "General", gender: "Male", age: 44, xp: 2050, rival_ids: [1, 7], badges_ids: [4, 5, 8, 10, 15], titles_ids: [10, 11, 15], cosmetic_ids: [1, 5, 9, 15], profile: '{"color":"/Avatar/color/image (2).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 3, username: "GeneralConfusion", first_name: "Sarah", last_name: "Jenkins", email: "sarah.j@outlook.com", password: defaultPassword, rank: "Col", gender: "Female", age: 41, xp: 2100, rival_ids: [1, 9], badges_ids: [1, 4, 5, 8, 14], titles_ids: [1, 14, 15], cosmetic_ids: [2, 8, 11], profile: '{"color":"/Avatar/color/image (3).png","base":"/Avatar/female.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 4, username: "TacticalNapTime", first_name: "Marcus", last_name: "Stone", email: "m.stone@army.mil", password: defaultPassword, rank: "LtCol", gender: "Male", age: 39, xp: 1950, rival_ids: [5, 10], badges_ids: [6, 7, 9, 10], titles_ids: [3, 6, 9], cosmetic_ids: [4, 7, 13], profile: '{"color":"/Avatar/color/image (4).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 5, username: "CaptainCrunchTime", first_name: "Alex", last_name: "Reed", email: "reed.a@gmail.com", password: defaultPassword, rank: "Maj", gender: "Male", age: 38, xp: 1800, rival_ids: [4, 11], badges_ids: [2, 11, 12, 13], titles_ids: [2, 5, 12], cosmetic_ids: [6, 14, 15], profile: '{"color":"/Avatar/color/image (5).png","base":"/Avatar/male.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 6, username: "SgtSnackz", first_name: "David", last_name: "Chen", email: "chen88@yahoo.com", password: defaultPassword, rank: "CMSgt", gender: "Male", age: 37, xp: 2650, rival_ids: [12, 15], badges_ids: [3, 4, 8], titles_ids: [4, 8], cosmetic_ids: [1, 10], profile: '{"color":"/Avatar/color/image (2).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 7, username: "The_Blue_Crayon_Tastes_Best", first_name: "Kevin", last_name: "O'Brien", email: "obrien.k@gmail.com", password: defaultPassword, rank: "SMSgt", gender: "Male", age: 36, xp: 1550, rival_ids: [2, 8], badges_ids: [1, 6, 14], titles_ids: [7, 13], cosmetic_ids: [3, 12], profile: '{"color":"/Avatar/color/image (1).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 8, username: "CorporalPunishment", first_name: "Elena", last_name: "Rodriguez", email: "elena.rod@gmail.com", password: defaultPassword, rank: "MSgt", gender: "Female", age: 34, xp: 1400, rival_ids: [7, 13], badges_ids: [2, 11, 13], titles_ids: [5, 12], cosmetic_ids: [6, 15], profile: '{"color":"/Avatar/color/image (2).png","base":"/Avatar/female.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 9, username: "RearAdmiralRust", first_name: "Tyson", last_name: "Fury", email: "tyson.f@hotmail.com", password: defaultPassword, rank: "TSgt", gender: "Male", age: 32, xp: 1300, rival_ids: [3, 10], badges_ids: [6, 9], titles_ids: [3, 9], cosmetic_ids: [4, 13], profile: '{"color":"/Avatar/color/image (3).png","base":"/Avatar/male.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 10, username: "POG_Life_Luxury", first_name: "Liam", last_name: "Smith", email: "liam.s@gmail.com", password: defaultPassword, rank: "Sgt", gender: "Male", age: 29, xp: 1200, rival_ids: [4, 9], badges_ids: [1, 13], titles_ids: [1], cosmetic_ids: [2], profile: '{"color":"/Avatar/color/image (4).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 11, username: "PrivatePains", first_name: "Chloe", last_name: "Davis", email: "chloe.d@yahoo.com", password: defaultPassword, rank: "Capt", gender: "Female", age: 31, xp: 1150, rival_ids: [5, 14], badges_ids: [7, 10], titles_ids: [6, 11], cosmetic_ids: [5, 14], profile: '{"color":"/Avatar/color/image (5).png","base":"/Avatar/female.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 12, username: "SgtSausage", first_name: "Zoe", last_name: "Wilson", email: "zoe.w@gmail.com", password: defaultPassword, rank: "1st Lt", gender: "Female", age: 28, xp: 1050, rival_ids: [6, 15], badges_ids: [5, 15], titles_ids: [10, 15], cosmetic_ids: [8, 11], profile: '{"color":"/Avatar/color/image.png","base":"/Avatar/female.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 13, username: "DishonorableDischarge", first_name: "Noah", last_name: "Brown", email: "noah.b@hotmail.com", password: defaultPassword, rank: "2nd Lt", gender: "Male", age: 26, xp: 950, rival_ids: [8, 16], badges_ids: [2, 12], titles_ids: [2, 5], cosmetic_ids: [9, 14], profile: '{"color":"/Avatar/color/image (1).png","base":"/Avatar/male.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 14, username: "GIGoJoe", first_name: "Mia", last_name: "Garcia", email: "mia.g@gmail.com", password: defaultPassword, rank: "Spc4", gender: "Female", age: 25, xp: 850, rival_ids: [11, 17], badges_ids: [3, 11], titles_ids: [4, 12], cosmetic_ids: [1, 7], profile: '{"color":"/Avatar/color/image (2).png","base":"/Avatar/female.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 15, username: "NinetyDay_Wonder", first_name: "James", last_name: "Johnson", email: "james.j@yahoo.com", password: defaultPassword, rank: "2nd Lt", gender: "Male", age: 24, xp: 750, rival_ids: [6, 12], badges_ids: [6, 13], titles_ids: [3], cosmetic_ids: [4], profile: '{"color":"/Avatar/color/image (3).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 16, username: "MRE_Gourmet", first_name: "Ethan", last_name: "Williams", email: "ethan.w@gmail.com", password: defaultPassword, rank: "Spc2", gender: "Male", age: 23, xp: 650, rival_ids: [13, 19], badges_ids: [1, 7], titles_ids: [1], cosmetic_ids: [2], profile: '{"color":"/Avatar/color/image (4).png","base":"/Avatar/male.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 17, username: "FullMetalJacket", first_name: "Ava", last_name: "Taylor", email: "ava.t@yahoo.com", password: defaultPassword, rank: "Spc1", gender: "Female", age: 22, xp: 550, rival_ids: [14, 20], badges_ids: [13], titles_ids: [], cosmetic_ids: [5], profile: '{"color":"/Avatar/color/image (5).png","base":"/Avatar/female.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 18, username: "DFAC_Destroyer", first_name: "Logan", last_name: "Anderson", email: "logan.a@hotmail.com", password: defaultPassword, rank: "Spc1", gender: "Male", age: 21, xp: 2450, rival_ids: [16, 21], badges_ids: [11], titles_ids: [], cosmetic_ids: [6], profile: '{"color":"/Avatar/color/image.png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 19, username: "MajorAttitude", first_name: "Isabella", last_name: "Thomas", email: "isabella.t@gmail.com", password: defaultPassword, rank: "Spc1", gender: "Female", age: 20, xp: 350, rival_ids: [16, 22], badges_ids: [12], titles_ids: [], cosmetic_ids: [7], profile: '{"color":"/Avatar/color/image (1).png","base":"/Avatar/female.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 20, username: "ShamShield_Elite", first_name: "Mason", last_name: "Jackson", email: "mason.j@yahoo.com", password: defaultPassword, rank: "Spc1", gender: "Male", age: 21, xp: 250, rival_ids: [], badges_ids: [], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image (2).png","base":"/Avatar/male.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 21, username: "NeonNinja", first_name: "Kai", last_name: "Suzuki", email: "kai.s@gmail.com", password: defaultPassword, rank: "Sgt", gender: "Male", age: 27, xp: 1100, rival_ids: [2, 3], badges_ids: [1, 2], titles_ids: [1], cosmetic_ids: [1, 2], profile: '{"color":"/Avatar/color/image (3).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 22, username: "OfficerObvious", first_name: "Mia", last_name: "Wong", email: "mia.w@gmail.com", password: defaultPassword, rank: "Spc4", gender: "Female", age: 24, xp: 980, rival_ids: [19, 23], badges_ids: [3], titles_ids: [4], cosmetic_ids: [7], profile: '{"color":"/Avatar/color/image (4).png","base":"/Avatar/female.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 23, username: "MRE_Sommelier", first_name: "Leo", last_name: "Vazquez", email: "leo.v@gmail.com", password: defaultPassword, rank: "Spc3", gender: "Male", age: 22, xp: 640, rival_ids: [22], badges_ids: [], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image (5).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 24, username: "Couch_Commando", first_name: "Jada", last_name: "Pinkett", email: "jada.p@gmail.com", password: defaultPassword, rank: "Spc2", gender: "Female", age: 23, xp: 420, rival_ids: [], badges_ids: [], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image.png","base":"/Avatar/female.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 25, username: "CadetCorndog", first_name: "Sven", last_name: "Olsen", email: "sven.o@gmail.com", password: defaultPassword, rank: "Spc1", gender: "Male", age: 19, xp: 210, rival_ids: [], badges_ids: [], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image (1).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 26, username: "Whiskey_Tango_Foxtrot", first_name: "Aiyana", last_name: "Cloud", email: "aiyana.c@gmail.com", password: defaultPassword, rank: "Sgt", gender: "Female", age: 29, xp: 1250, rival_ids: [21, 28], badges_ids: [1, 5], titles_ids: [5], cosmetic_ids: [3], profile: '{"color":"/Avatar/color/image (2).png","base":"/Avatar/female.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 27, username: "ButterBar_Blunder", first_name: "Bao", last_name: "Nguyen", email: "bao.n@gmail.com", password: defaultPassword, rank: "Maj", gender: "Male", age: 40, xp: 1850, rival_ids: [4, 5], badges_ids: [1, 2, 8], titles_ids: [1, 2], cosmetic_ids: [5, 6], profile: '{"color":"/Avatar/color/image (3).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 28, username: "Negative_Ghostrider", first_name: "Lila", last_name: "Vance", email: "lila.v@gmail.com", password: defaultPassword, rank: "1st Lt", gender: "Female", age: 26, xp: 1020, rival_ids: [26, 29], badges_ids: [1, 6], titles_ids: [6], cosmetic_ids: [8], profile: '{"color":"/Avatar/color/image (4).png","base":"/Avatar/female.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 29, username: "CaptainObvious", first_name: "Rico", last_name: "Blaze", email: "rico.b@gmail.com", password: defaultPassword, rank: "Capt", gender: "Male", age: 33, xp: 1480, rival_ids: [28, 30], badges_ids: [2, 7], titles_ids: [7], cosmetic_ids: [9], profile: '{"color":"/Avatar/color/image (5).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 30, username: "SgtStubby", first_name: "Jade", last_name: "Lee", email: "jade.l@gmail.com", password: defaultPassword, rank: "Sgt", gender: "Female", age: 28, xp: 1140, rival_ids: [29, 31], badges_ids: [2, 8], titles_ids: [8], cosmetic_ids: [10], profile: '{"color":"/Avatar/color/image.png","base":"/Avatar/female.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 31, username: "PvtPartz", first_name: "Silas", last_name: "Vane", email: "silas.v@gmail.com", password: defaultPassword, rank: "Spc4", gender: "Male", age: 25, xp: 890, rival_ids: [30], badges_ids: [9], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image (1).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 32, username: "MajorLeeConfused", first_name: "Marina", last_name: "Blue", email: "marina.b@gmail.com", password: defaultPassword, rank: "Spc3", gender: "Female", age: 22, xp: 670, rival_ids: [33], badges_ids: [10], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image (2).png","base":"/Avatar/female.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 33, username: "FlakJacket", first_name: "Brock", last_name: "Hardy", email: "brock.h@gmail.com", password: defaultPassword, rank: "Spc2", gender: "Male", age: 21, xp: 440, rival_ids: [], badges_ids: [], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image (3).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 34, username: "StealthyTaco", first_name: "Luna", last_name: "Grey", email: "luna.g@gmail.com", password: defaultPassword, rank: "Spc1", gender: "Female", age: 19, xp: 230, rival_ids: [], badges_ids: [], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image (4).png","base":"/Avatar/female.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 35, username: "Sgt_Sarcasm", first_name: "Cole", last_name: "Ash", email: "cole.a@gmail.com", password: defaultPassword, rank: "TSgt", gender: "Male", age: 31, xp: 1320, rival_ids: [9, 36], badges_ids: [3, 11], titles_ids: [11], cosmetic_ids: [12], profile: '{"color":"/Avatar/color/image (5).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 36, username: "CaptainCamouflage", first_name: "Elsa", last_name: "Snow", email: "elsa.s@gmail.com", password: defaultPassword, rank: "Sgt", gender: "Female", age: 27, xp: 1190, rival_ids: [35, 37], badges_ids: [4, 12], titles_ids: [12], cosmetic_ids: [13], profile: '{"color":"/Avatar/color/image.png","base":"/Avatar/female.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 37, username: "BulletToothTony", first_name: "Drake", last_name: "Sly", email: "drake.s@gmail.com", password: defaultPassword, rank: "MSgt", gender: "Male", age: 35, xp: 2490, rival_ids: [36, 38], badges_ids: [5, 13], titles_ids: [13], cosmetic_ids: [14], profile: '{"color":"/Avatar/color/image (1).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 38, username: "AuraArcher", first_name: "Kira", last_name: "Light", email: "kira.l@gmail.com", password: defaultPassword, rank: "Capt", gender: "Female", age: 29, xp: 1410, rival_ids: [37, 39], badges_ids: [6, 14], titles_ids: [14], cosmetic_ids: [15], profile: '{"color":"/Avatar/color/image (2).png","base":"/Avatar/female.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 39, username: "GeneralMills", first_name: "Xander", last_name: "Dark", email: "xander.d@gmail.com", password: defaultPassword, rank: "Maj", gender: "Male", age: 41, xp: 1910, rival_ids: [38, 40], badges_ids: [7, 15], titles_ids: [15], cosmetic_ids: [1], profile: '{"color":"/Avatar/color/image (3).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 40, username: "DD214_Awaiter", first_name: "Jean", last_name: "Grey", email: "jean.g@gmail.com", password: defaultPassword, rank: "Col", gender: "Female", age: 38, xp: 2050, rival_ids: [39, 41], badges_ids: [1, 8], titles_ids: [1, 4], cosmetic_ids: [2, 3], profile: '{"color":"/Avatar/color/image (4).png","base":"/Avatar/female.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 41, username: "Leatherneck_Larry", first_name: "Larry", last_name: "Stone", email: "larry.s@gmail.com", password: defaultPassword, rank: "Sgt", gender: "Male", age: 26, xp: 1080, rival_ids: [40, 42], badges_ids: [2, 9], titles_ids: [2, 5], cosmetic_ids: [4], profile: '{"color":"/Avatar/color/image (5).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 42, username: "LunarLancer", first_name: "Selene", last_name: "Moon", email: "selene.m@gmail.com", password: defaultPassword, rank: "Spc4", gender: "Female", age: 23, xp: 910, rival_ids: [41, 43], badges_ids: [3, 10], titles_ids: [3, 6], cosmetic_ids: [5], profile: '{"color":"/Avatar/color/image.png","base":"/Avatar/female.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 43, username: "GomerPyle", first_name: "Thor", last_name: "Odinson", email: "thor.o@gmail.com", password: defaultPassword, rank: "Spc3", gender: "Male", age: 22, xp: 720, rival_ids: [42], badges_ids: [], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image (1).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 44, username: "PrivatelyAmused", first_name: "Wanda", last_name: "Maxim", email: "wanda.m@gmail.com", password: defaultPassword, rank: "Spc2", gender: "Female", age: 21, xp: 490, rival_ids: [45], badges_ids: [], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image (2).png","base":"/Avatar/female.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 45, username: "IronInquisitor", first_name: "Tony", last_name: "Stark", email: "tony.s@gmail.com", password: defaultPassword, rank: "Spc1", gender: "Male", age: 19, xp: 240, rival_ids: [], badges_ids: [], titles_ids: [], cosmetic_ids: [], profile: '{"color":"/Avatar/color/image (3).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 46, username: "SylvanSentinel", first_name: "Diana", last_name: "Prince", email: "diana.p@gmail.com", password: defaultPassword, rank: "Sgt", gender: "Female", age: 28, xp: 1220, rival_ids: [26, 47], badges_ids: [5, 11], titles_ids: [11], cosmetic_ids: [7], profile: '{"color":"/Avatar/color/image (4).png","base":"/Avatar/female.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 47, username: "Xx_CaptAmerica_xX", first_name: "Steve", last_name: "Rogers", email: "steve.r@gmail.com", password: defaultPassword, rank: "Capt", gender: "Male", age: 34, xp: 1440, rival_ids: [46, 48], badges_ids: [6, 12], titles_ids: [12], cosmetic_ids: [8], profile: '{"color":"/Avatar/color/image (5).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 48, username: "GarnetGale", first_name: "Nat", last_name: "Roman", email: "nat.r@gmail.com", password: defaultPassword, rank: "1st Lt", gender: "Female", age: 26, xp: 1060, rival_ids: [47, 49], badges_ids: [7, 13], titles_ids: [13], cosmetic_ids: [9], profile: '{"color":"/Avatar/color/image.png","base":"/Avatar/female.png","head":"/Avatar/headband.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/headphones.png"]}' },
  { id: 49, username: "BatmanInBoots", first_name: "Bruce", last_name: "Wayne", email: "bruce.w@gmail.com", password: defaultPassword, rank: "Maj", gender: "Male", age: 39, xp: 1880, rival_ids: [48, 50], badges_ids: [8, 14], titles_ids: [14], cosmetic_ids: [10], profile: '{"color":"/Avatar/color/image (1).png","base":"/Avatar/male.png","head":"/Avatar/beanie.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/chain.png"]}' },
  { id: 50, username: "SgtSparkles", first_name: "Carol", last_name: "Danvers", email: "carol.d@gmail.com", password: defaultPassword, rank: "Col", gender: "Female", age: 36, xp: 2150, rival_ids: [49, 51], badges_ids: [9, 15], titles_ids: [15], cosmetic_ids: [11], profile: '{"color":"/Avatar/color/image (2).png","base":"/Avatar/female.png","head":"/Avatar/wreath.png","chosenGloves":"/Avatar/gloves2.png","chosenMisc":["/Avatar/outline.png"]}' },
  { id: 51, username: "Keyboard_Commando", first_name: "TChalla", last_name: "King", email: "tchalla.k@gmail.com", password: defaultPassword, rank: "General", gender: "Male", age: 40, xp: 2760, rival_ids: [50, 1], badges_ids: [10, 1], titles_ids: [1], cosmetic_ids: [12], profile: '{"color":"/Avatar/color/image (3).png","base":"/Avatar/male.png","head":"/Avatar/hat.png","chosenGloves":"/Avatar/gloves.png","chosenMisc":["/Avatar/headphones.png"]}' }
];


};
