const bcrypt = require("bcrypt");
const SALT_ROUNDS = 10;

module.exports = async () => {
  const defaultPassword = await bcrypt.hash("password", SALT_ROUNDS);
  const adminPassword = await bcrypt.hash("123", SALT_ROUNDS);
  return [
    // ADMIN
    {
      id: 1,
      is_admin: true,
      username: "EmperorMatthew",
      first_name: "Matthew",
      last_name: "Wegenke",
      email: "abc@gmail.com",
      password: adminPassword,
      rank: "General",
      gender: "Male",
      age: 67,
      xp: 2500,
      rival_ids: [2, 3, 4],
      badges_ids: [1, 2, 5, 10, 15],
      titles_ids: [1, 2, 15],
      cosmetic_ids: [3, 4, 10, 12],
    },
    // HIGH XP / HIGH RANK (Ages 38-45)
    {
      id: 2,
      username: "VanguardPrime",
      first_name: "John",
      last_name: "Miller",
      email: "vanguard@gmail.com",
      password: defaultPassword,
      rank: "General",
      gender: "Male",
      age: 44,
      xp: 2450,
      rival_ids: [1, 7],
      badges_ids: [4, 5, 8, 10, 15],
      titles_ids: [10, 11, 15],
      cosmetic_ids: [1, 5, 9, 15],
    },
    {
      id: 3,
      username: "LadySentinel",
      first_name: "Sarah",
      last_name: "Jenkins",
      email: "sarah.j@outlook.com",
      password: defaultPassword,
      rank: "Col",
      gender: "Female",
      age: 41,
      xp: 2100,
      rival_ids: [1, 9],
      badges_ids: [1, 4, 5, 8, 14],
      titles_ids: [1, 14, 15],
      cosmetic_ids: [2, 8, 11],
    },
    {
      id: 4,
      username: "IronAegis",
      first_name: "Marcus",
      last_name: "Stone",
      email: "m.stone@army.mil",
      password: defaultPassword,
      rank: "LtCol",
      gender: "Male",
      age: 39,
      xp: 1950,
      rival_ids: [5, 10],
      badges_ids: [6, 7, 9, 10],
      titles_ids: [3, 6, 9],
      cosmetic_ids: [4, 7, 13],
    },
    {
      id: 5,
      username: "GhostStalker",
      first_name: "Alex",
      last_name: "Reed",
      email: "reed.a@gmail.com",
      password: defaultPassword,
      rank: "Maj",
      gender: "Male",
      age: 38,
      xp: 1800,
      rival_ids: [4, 11],
      badges_ids: [2, 11, 12, 13],
      titles_ids: [2, 5, 12],
      cosmetic_ids: [6, 14, 15],
    },
    {
      id: 6,
      username: "xX_Wraith_Xx",
      first_name: "David",
      last_name: "Chen",
      email: "chen88@yahoo.com",
      password: defaultPassword,
      rank: "CMSgt",
      gender: "Male",
      age: 37,
      xp: 1650,
      rival_ids: [12, 15],
      badges_ids: [3, 4, 8],
      titles_ids: [4, 8],
      cosmetic_ids: [1, 10],
    },
    {
      id: 7,
      username: "SgtSnackz",
      first_name: "Kevin",
      last_name: "O'Brien",
      email: "obrien.k@gmail.com",
      password: defaultPassword,
      rank: "SMSgt",
      gender: "Male",
      age: 36,
      xp: 1550,
      rival_ids: [2, 8],
      badges_ids: [1, 6, 14],
      titles_ids: [7, 13],
      cosmetic_ids: [3, 12],
    },
    {
      id: 8,
      username: "NebulaKnight",
      first_name: "Elena",
      last_name: "Rodriguez",
      email: "elena.rod@gmail.com",
      password: defaultPassword,
      rank: "MSgt",
      gender: "Female",
      age: 34,
      xp: 1400,
      rival_ids: [7, 13],
      badges_ids: [2, 11, 13],
      titles_ids: [5, 12],
      cosmetic_ids: [6, 15],
    },
    {
      id: 9,
      username: "BulletProof",
      first_name: "Tyson",
      last_name: "Fury",
      email: "tyson.f@hotmail.com",
      password: defaultPassword,
      rank: "TSgt",
      gender: "Male",
      age: 32,
      xp: 1300,
      rival_ids: [3, 10],
      badges_ids: [6, 9],
      titles_ids: [3, 9],
      cosmetic_ids: [4, 13],
    },
    {
      id: 10,
      username: "CipherZero",
      first_name: "Liam",
      last_name: "Smith",
      email: "liam.s@gmail.com",
      password: defaultPassword,
      rank: "Sgt",
      gender: "Male",
      age: 29,
      xp: 1200,
      rival_ids: [4, 9],
      badges_ids: [1, 13],
      titles_ids: [1],
      cosmetic_ids: [2],
    },
    {
      id: 11,
      username: "TitaniumTitan",
      first_name: "Chloe",
      last_name: "Davis",
      email: "chloe.d@yahoo.com",
      password: defaultPassword,
      rank: "Capt",
      gender: "Female",
      age: 31,
      xp: 1150,
      rival_ids: [5, 14],
      badges_ids: [7, 10],
      titles_ids: [6, 11],
      cosmetic_ids: [5, 14],
    },
    {
      id: 12,
      username: "ShadowRunner",
      first_name: "Zoe",
      last_name: "Wilson",
      email: "zoe.w@gmail.com",
      password: defaultPassword,
      rank: "1st Lt",
      gender: "Female",
      age: 28,
      xp: 1050,
      rival_ids: [6, 15],
      badges_ids: [5, 15],
      titles_ids: [10, 15],
      cosmetic_ids: [8, 11],
    },
    {
      id: 13,
      username: "EchoStrike",
      first_name: "Noah",
      last_name: "Brown",
      email: "noah.b@hotmail.com",
      password: defaultPassword,
      rank: "2nd Lt",
      gender: "Male",
      age: 26,
      xp: 950,
      rival_ids: [8, 16],
      badges_ids: [2, 12],
      titles_ids: [2, 5],
      cosmetic_ids: [9, 14],
    },
    {
      id: 14,
      username: "VoltViper",
      first_name: "Mia",
      last_name: "Garcia",
      email: "mia.g@gmail.com",
      password: defaultPassword,
      rank: "Spc4",
      gender: "Female",
      age: 25,
      xp: 850,
      rival_ids: [11, 17],
      badges_ids: [3, 11],
      titles_ids: [4, 12],
      cosmetic_ids: [1, 7],
    },
    {
      id: 15,
      username: "RapidRavage",
      first_name: "James",
      last_name: "Johnson",
      email: "james.j@yahoo.com",
      password: defaultPassword,
      rank: "Spc3",
      gender: "Male",
      age: 24,
      xp: 750,
      rival_ids: [6, 12],
      badges_ids: [6, 13],
      titles_ids: [3],
      cosmetic_ids: [4],
    },
    {
      id: 16,
      username: "KiloKing",
      first_name: "Ethan",
      last_name: "Williams",
      email: "ethan.w@gmail.com",
      password: defaultPassword,
      rank: "Spc2",
      gender: "Male",
      age: 23,
      xp: 650,
      rival_ids: [13, 19],
      badges_ids: [1, 7],
      titles_ids: [1],
      cosmetic_ids: [2],
    },
    {
      id: 17,
      username: "AlphaAura",
      first_name: "Ava",
      last_name: "Taylor",
      email: "ava.t@yahoo.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Female",
      age: 22,
      xp: 550,
      rival_ids: [14, 20],
      badges_ids: [13],
      titles_ids: [],
      cosmetic_ids: [5],
    },
    {
      id: 18,
      username: "DeltaDoom",
      first_name: "Logan",
      last_name: "Anderson",
      email: "logan.a@hotmail.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Male",
      age: 21,
      xp: 450,
      rival_ids: [16, 21],
      badges_ids: [11],
      titles_ids: [],
      cosmetic_ids: [6],
    },
    {
      id: 19,
      username: "ZodiacZero",
      first_name: "Isabella",
      last_name: "Thomas",
      email: "isabella.t@gmail.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Female",
      age: 20,
      xp: 350,
      rival_ids: [16, 22],
      badges_ids: [12],
      titles_ids: [],
      cosmetic_ids: [7],
    },
    {
      id: 20,
      username: "RogueRebel",
      first_name: "Mason",
      last_name: "Jackson",
      email: "mason.j@yahoo.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Male",
      age: 19,
      xp: 250,
      rival_ids: [17, 23],
      badges_ids: [13],
      titles_ids: [],
      cosmetic_ids: [8],
    },
    {
      id: 21,
      username: "PhantomProwler",
      first_name: "Sophia",
      last_name: "White",
      email: "sophia.w@gmail.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Female",
      age: 18,
      xp: 150,
      rival_ids: [18, 24],
      badges_ids: [],
      titles_ids: [],
      cosmetic_ids: [9],
    },
    {
      id: 22,
      username: "Blazeit99",
      first_name: "Lucas",
      last_name: "Harris",
      email: "l.harris@gmail.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Male",
      age: 20,
      xp: 200,
      rival_ids: [19],
      badges_ids: [13],
      titles_ids: [],
      cosmetic_ids: [1],
    },
    {
      id: 23,
      username: "GrimmFate",
      first_name: "Lily",
      last_name: "Martin",
      email: "lily.m@yahoo.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Female",
      age: 21,
      xp: 300,
      rival_ids: [20],
      badges_ids: [11],
      titles_ids: [],
      cosmetic_ids: [2],
    },
    {
      id: 24,
      username: "StormChaser",
      first_name: "Oliver",
      last_name: "Thompson",
      email: "oliver.t@gmail.com",
      password: defaultPassword,
      rank: "Spc2",
      gender: "Male",
      age: 22,
      xp: 400,
      rival_ids: [21],
      badges_ids: [1, 13],
      titles_ids: [1],
      cosmetic_ids: [3],
    },
    {
      id: 25,
      username: "CyberSoul",
      first_name: "Emma",
      last_name: "Moore",
      email: "emma.m@hotmail.com",
      password: defaultPassword,
      rank: "Spc3",
      gender: "Female",
      age: 23,
      xp: 500,
      rival_ids: [26],
      badges_ids: [3, 11],
      titles_ids: [4],
      cosmetic_ids: [4],
    },
    {
      id: 26,
      username: "ApexHunter",
      first_name: "Jackson",
      last_name: "Young",
      email: "j.young@gmail.com",
      password: defaultPassword,
      rank: "Spc4",
      gender: "Male",
      age: 24,
      xp: 600,
      rival_ids: [25],
      badges_ids: [6, 13],
      titles_ids: [3],
      cosmetic_ids: [5],
    },
    {
      id: 27,
      username: "MysticMage",
      first_name: "Aria",
      last_name: "Allen",
      email: "aria.a@yahoo.com",
      password: defaultPassword,
      rank: "Sgt",
      gender: "Female",
      age: 27,
      xp: 1100,
      rival_ids: [28],
      badges_ids: [1, 7, 10],
      titles_ids: [1, 6],
      cosmetic_ids: [6],
    },
    {
      id: 28,
      username: "IronHeart",
      first_name: "Henry",
      last_name: "King",
      email: "henry.k@gmail.com",
      password: defaultPassword,
      rank: "Sgt",
      gender: "Male",
      age: 29,
      xp: 1250,
      rival_ids: [27],
      badges_ids: [4, 9, 14],
      titles_ids: [9, 14],
      cosmetic_ids: [7],
    },
    {
      id: 29,
      username: "DarkKnight",
      first_name: "Sebastian",
      last_name: "Wright",
      email: "s.wright@hotmail.com",
      password: defaultPassword,
      rank: "TSgt",
      gender: "Male",
      age: 31,
      xp: 1350,
      rival_ids: [30],
      badges_ids: [2, 5, 8],
      titles_ids: [10, 11],
      cosmetic_ids: [8],
    },
    {
      id: 30,
      username: "LunarLuna",
      first_name: "Luna",
      last_name: "Scott",
      email: "luna.s@gmail.com",
      password: defaultPassword,
      rank: "MSgt",
      gender: "Female",
      age: 33,
      xp: 1450,
      rival_ids: [29],
      badges_ids: [11, 12, 15],
      titles_ids: [12, 15],
      cosmetic_ids: [9],
    },
    {
      id: 31,
      username: "SolarSky",
      first_name: "Aurora",
      last_name: "Green",
      email: "aurora.g@yahoo.com",
      password: defaultPassword,
      rank: "SMSgt",
      gender: "Female",
      age: 35,
      xp: 1600,
      rival_ids: [32],
      badges_ids: [4, 8, 10],
      titles_ids: [1, 2],
      cosmetic_ids: [10],
    },
    {
      id: 32,
      username: "TerraTitan",
      first_name: "Caleb",
      last_name: "Baker",
      email: "caleb.b@gmail.com",
      password: defaultPassword,
      rank: "CMSgt",
      gender: "Male",
      age: 37,
      xp: 1700,
      rival_ids: [31],
      badges_ids: [5, 9, 15],
      titles_ids: [14, 15],
      cosmetic_ids: [11],
    },
    {
      id: 33,
      username: "AquaAce",
      first_name: "Gabriel",
      last_name: "Adams",
      email: "gabriel.a@hotmail.com",
      password: defaultPassword,
      rank: "2nd Lt",
      gender: "Male",
      age: 25,
      xp: 900,
      rival_ids: [34],
      badges_ids: [2, 13],
      titles_ids: [5],
      cosmetic_ids: [12],
    },
    {
      id: 34,
      username: "PyroPulse",
      first_name: "Stella",
      last_name: "Campbell",
      email: "stella.c@gmail.com",
      password: defaultPassword,
      rank: "1st Lt",
      gender: "Female",
      age: 27,
      xp: 1000,
      rival_ids: [33],
      badges_ids: [11, 14],
      titles_ids: [12],
      cosmetic_ids: [13],
    },
    {
      id: 35,
      username: "WindWalker",
      first_name: "Mateo",
      last_name: "Nelson",
      email: "mateo.n@yahoo.com",
      password: defaultPassword,
      rank: "Capt",
      gender: "Male",
      age: 30,
      xp: 1100,
      rival_ids: [36],
      badges_ids: [1, 6],
      titles_ids: [1, 3],
      cosmetic_ids: [14],
    },
    {
      id: 36,
      username: "StoneSovereign",
      first_name: "Elena",
      last_name: "Carter",
      email: "elena.c@gmail.com",
      password: defaultPassword,
      rank: "Maj",
      gender: "Female",
      age: 34,
      xp: 1750,
      rival_ids: [35],
      badges_ids: [4, 8, 10, 15],
      titles_ids: [11, 15],
      cosmetic_ids: [15],
    },
    {
      id: 37,
      username: "ShadowStep",
      first_name: "Julian",
      last_name: "Mitchell",
      email: "j.mitchell@hotmail.com",
      password: defaultPassword,
      rank: "LtCol",
      gender: "Male",
      age: 38,
      xp: 1900,
      rival_ids: [38],
      badges_ids: [5, 9, 14, 15],
      titles_ids: [10, 14],
      cosmetic_ids: [1],
    },
    {
      id: 38,
      username: "IronImperial",
      first_name: "Gianna",
      last_name: "Perez",
      email: "gianna.p@gmail.com",
      password: defaultPassword,
      rank: "Col",
      gender: "Female",
      age: 41,
      xp: 2050,
      rival_ids: [37],
      badges_ids: [1, 5, 8, 10, 15],
      titles_ids: [1, 15],
      cosmetic_ids: [2],
    },
    {
      id: 39,
      username: "VanguardValiant",
      first_name: "Dominic",
      last_name: "Roberts",
      email: "d.roberts@yahoo.com",
      password: defaultPassword,
      rank: "General",
      gender: "Male",
      age: 45,
      xp: 2300,
      rival_ids: [1, 2],
      badges_ids: [4, 5, 8, 10, 15],
      titles_ids: [11, 15],
      cosmetic_ids: [3],
    },
    {
      id: 40,
      username: "ZenithZoner",
      first_name: "Maya",
      last_name: "Turner",
      email: "maya.t@gmail.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Female",
      age: 19,
      xp: 100,
      rival_ids: [41],
      badges_ids: [13],
      titles_ids: [],
      cosmetic_ids: [4],
    },
    {
      id: 41,
      username: "ApexAbyss",
      first_name: "Ryan",
      last_name: "Phillips",
      email: "ryan.p@hotmail.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Male",
      age: 19,
      xp: 120,
      rival_ids: [40],
      badges_ids: [11],
      titles_ids: [],
      cosmetic_ids: [5],
    },
    {
      id: 42,
      username: "BulletBlitz",
      first_name: "Hailey",
      last_name: "Campbell",
      email: "hailey.c@gmail.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Female",
      age: 20,
      xp: 180,
      rival_ids: [43],
      badges_ids: [13],
      titles_ids: [],
      cosmetic_ids: [6],
    },
    {
      id: 43,
      username: "CipherChaos",
      first_name: "Adam",
      last_name: "Parker",
      email: "adam.p@yahoo.com",
      password: defaultPassword,
      rank: "Spc1",
      gender: "Male",
      age: 20,
      xp: 220,
      rival_ids: [42],
      badges_ids: [12],
      titles_ids: [],
      cosmetic_ids: [7],
    },
    {
      id: 44,
      username: "DeltaDash",
      first_name: "Kaitlyn",
      last_name: "Evans",
      email: "k.evans@gmail.com",
      password: defaultPassword,
      rank: "Spc2",
      gender: "Female",
      age: 22,
      xp: 350,
      rival_ids: [45],
      badges_ids: [1, 13],
      titles_ids: [1],
      cosmetic_ids: [8],
    },
    {
      id: 45,
      username: "EchoEdge",
      first_name: "Brayden",
      last_name: "Edwards",
      email: "b.edwards@hotmail.com",
      password: defaultPassword,
      rank: "Spc2",
      gender: "Male",
      age: 22,
      xp: 380,
      rival_ids: [44],
      badges_ids: [11, 12],
      titles_ids: [],
      cosmetic_ids: [9],
    },
    {
      id: 46,
      username: "FrostFury",
      first_name: "Brooklynn",
      last_name: "Collins",
      email: "b.collins@gmail.com",
      password: defaultPassword,
      rank: "Spc3",
      gender: "Female",
      age: 23,
      xp: 480,
      rival_ids: [47],
      badges_ids: [3, 11, 13],
      titles_ids: [4],
      cosmetic_ids: [10],
    },
    {
      id: 47,
      username: "GhostGrit",
      first_name: "Gavin",
      last_name: "Stewart",
      email: "g.stewart@yahoo.com",
      password: defaultPassword,
      rank: "Spc3",
      gender: "Male",
      age: 23,
      xp: 510,
      rival_ids: [46],
      badges_ids: [6, 12, 13],
      titles_ids: [3],
      cosmetic_ids: [11],
    },
    {
      id: 48,
      username: "HyperHustle",
      first_name: "Allison",
      last_name: "Morris",
      email: "a.morris@gmail.com",
      password: defaultPassword,
      rank: "Spc4",
      gender: "Female",
      age: 24,
      xp: 620,
      rival_ids: [49],
      badges_ids: [1, 3, 11, 13],
      titles_ids: [1, 4],
      cosmetic_ids: [12],
    },
    {
      id: 49,
      username: "IronInstinct",
      first_name: "Jaxon",
      last_name: "Rogers",
      email: "j.rogers@hotmail.com",
      password: defaultPassword,
      rank: "Spc4",
      gender: "Male",
      age: 24,
      xp: 650,
      rival_ids: [48],
      badges_ids: [6, 7, 12, 14],
      titles_ids: [3, 7],
      cosmetic_ids: [13],
    },
    {
      id: 50,
      username: "JadeJuggernaut",
      first_name: "Madelyn",
      last_name: "Reed",
      email: "m.reed@gmail.com",
      password: defaultPassword,
      rank: "Sgt",
      gender: "Female",
      age: 28,
      xp: 1180,
      rival_ids: [51],
      badges_ids: [1, 4, 10, 15],
      titles_ids: [1, 2, 15],
      cosmetic_ids: [14],
    },
    {
      id: 51,
      username: "KrypticKnight",
      first_name: "Bentley",
      last_name: "Cook",
      email: "b.cook@yahoo.com",
      password: defaultPassword,
      rank: "Sgt",
      gender: "Male",
      age: 29,
      xp: 1220,
      rival_ids: [50],
      badges_ids: [6, 8, 9, 14],
      titles_ids: [3, 8, 14],
      cosmetic_ids: [15],
    },
  ];
};
